### ISSUE TITLE
Interested in other kingston firmware?

### ISSUE THREAD

**Issue by duck7000** [vulgo/kingston-a2000-firmware-bin-linux#4]
Recently i got a kingston KC2000 m2 ssd with old firmware.
So i contacted Kingston and they send me a new firmware for this device and it works great.

Would you be interested in adding this firmware to this repo? 
To help others who have firmware issues.

I can give you the link they send me but i don't know how long it will be valid.
II don't know how to verify that this firmware is legit but it comes directly from kingston support

**Comment by vulgo** [comment]
I'm not, my reasoning is Kingston shipped a load of A2000's with a firmware where APST would cause a failure requiring an NVME device power cycle to bring the system back up.

Windows was superficially unaffected because Windows doesn't enable APST by default.

This repo is here because Kingston don't provide a download on their website for non-Windows systems, it's named and texted specifically to help Google index it for the A2000 users looking for the firmware that fixes that APST issue and don't mind trusting a firmware that doesn't come directly from Kingston.

I'd encourage you to set up a similar repo for your drive if you agree with my reasoning. My opinion is that it is a failure on the part of Kingston not to provide easy Linux firmware updates for their devices, especially ones that bring critical bug fixes like the one described above.

**Comment by duck7000** [comment]
I perfectly understand your stand of view, and yes Kingston should not be so difficult about firmware upgrades for Linux users i agree.

I do have a github account and i will set up a repo for KC2000 firmware just to help others.

Thanks for your comments!
